Functions jd mr
learn-academy-2022-foxtrot/javascript-intro-challenges pull request #27
Opened 2022-09-12 23:26 UTC by rhodesmt

2022-09-12 23:27 UTC, elysemontano requested changes
It looks like part of week 1 assessment is being pushed up to this PR

2022-09-12 23:28 UTC, rhodesmt reviewed
I'm not sure why that keeps getting pushed with these.

2022-09-12 23:48 UTC, rhodesmt reviewed
Alright the assessment has been removed. I used git add . instead of git add <file name> so it was uploading everything that I had open in my editor. Should be ready for merge now

2022-09-27 23:32 UTC, elysemontano approved these changes

2022-09-27 23:33 UTC, merged