Functions loops df cp
learn-academy-2022-foxtrot/javascript-intro-challenges pull request #49
Opened 2022-09-13 23:45 UTC by tawnchan

completed some challenges, will work on it some more.

2022-09-13 23:47 UTC, triciasykes requested changes
You pushed multiple files

2022-09-13 23:47 UTC, elysemontano requested changes
Do you need the empty file called javascript-functions.js?

2022-09-13 23:49 UTC, tawnchan commented
> You pushed multiple files

i don't understand what i need to do

2022-09-14 00:38 UTC, elysemontano approved these changes

2022-09-14 00:38 UTC, triciasykes approved these changes

2022-09-14 00:44 UTC, merged